# int("5")
# val = float(input("Enter some value :"))
# print(type(val),val)
name = input("enter name :")
age = int(input("enter age :"))
marks = float(input("enter marks :"))
print("Welcom",name)
print("Your Age",age)
print("Your marks",marks)
print("Exllent")