str = "i am studing python from apna college."
print(str)
str1 = str.capitalize()
print(str.endswith("ege."))
print(str.endswith("ege"))
print(str.endswith("."))
print(str)
print("(The first latter of the sentance is capital:)")
print(str1.capitalize())
print(str.find("from"))
print(str.find("apna"))
print(str.find("college"))
print(str.find("e"))
print(str.find("w"))
print("(Replaced latter python to javascript:)")
print(str.replace("python","javascript"))
print("To print string count:")
print(str.count("a"))
print(str.count("e"))
print(str.count("o"))
print(str.count("am"))
print(str.count("from"))
