collection = set()
print(type(collection))
collection.add(1)
collection.add(2)
collection.add("Hashim")
collection.add((7,8,9))
print(collection)
print(len(collection))
collection.remove(1)
print(collection)
print(len(collection))
collection.clear()
print(collection)
print(len(collection))
